# ============================================================================ #
#                              P r e - C o m m i t
# ============================================================================ #
fail_fast: false


repos:


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      # Security
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # Git secrets Leaks
  - repo: https://github.com/awslabs/git-secrets.git
    rev: 5357e18
    hooks:
      - id: git-secrets
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: mdl
        args: [-s, .mdl.rb]
        language: ruby
        files: \.(md|mdown|markdown)$
