#!/usr/bin/env bash
# ============================================================================ #
#                           P y t h o n   D i r E n v
# ============================================================================ #
set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

for venv in "$PWD/venv" "$HOME/venv"; do
    if [ -f "$venv/bin/activate" ]; then
        echo
        echo "Virtualenv directory found in: $venv"
        echo
        echo "Activating Virtualenv inside the directory: $venv"

        source "$venv/bin/activate"
        break
    fi
done
