#!/usr/bin/env d2 --theme 200 --sketch
#
#  vim:ts=2:sts=2:sw=2:et:filetype=d2

title: {
  label: "I don't always test my code...\nbut when I do...\nI do it the only way... in Production!"
  near: top-center
  shape: text
  style.font-size: 40
}

classes: {
  meme: {
    icon: images/production-meme.jpg
    shape: image
  }
}

Dev 1.class: meme
Dev 2.class: meme
Dev 3.class: meme

Dev 1 -> CI/CD: feature 1 {style.animated: true}
Dev 2 -> CI/CD: feature 2 {style.animated: true}
Dev 3 -> CI/CD: feature 3 {style.animated: true}

CI/CD -> Prod: {style.animated: true}
CI/CD.shape: diamond

  
