#!/usr/bin/env d2 --theme 200
# ============================================================================ #
#                  K u b e r n e t e s   O n - p r e m i s e
# ============================================================================ #

# Explicitly set the layout direction or change to a grid
direction: right

title: {
  label: Kubernetes On-Premise
  near: top-center
  shape: text
  style.font-size: 40
  style.underline: true
}

# Define classes for reusable node styles
classes: {
  dns: {
    label: DNS
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20DNS.svg
    shape: image
    style.icon-size: 60
  }
  network: {
    icon: https://diagrams.mingrammer.com/img/resources/gcp/network/routes.png
    shape: image
    style.icon-size: 60
  }
  storage: {
    label: "HA Networked Storage\nfor Kubernetes\nPersistent Volumes"
    icon: https://icons.terrastruct.com/azure%2FStorage%20Service%20Color%2FGeneral%20Storage.svg
    shape: image
    style.icon-size: 60
  }
  load_balancer: {
    label: "HA Load Balancer\n(HAProxy / Nginx / Traefik / Kong)"
    icon: https://diagrams.mingrammer.com/img/resources/onprem/network/haproxy.png
    shape: image
    style.icon-size: 60
  }
  k8s: {
    icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg
    shape: image
    style.icon-size: 60
  }
  server: {
    icon: https://icons.terrastruct.com/essentials%2F112-server.svg
    shape: image
    style.icon-size: 60
  }
}

# Define users, DNS, and network connections
users -> DNS -> user_network
DNS.class: dns

users: Users {
  icon: https://icons.terrastruct.com/essentials%2F359-users.svg
  shape: image
}

user_network: Network {class: network}

# Use columns to align the load balancers
group: {
  label: Load Balancers
  direction: down

  lb1: {class: load_balancer}
  lb2: {class: load_balancer}
}

user_network -> lb1
user_network -> lb2

lb1 -> network
lb2 -> network

network: Network {
  class: network
}

# Servers with Kubernetes nodes grouped in a column
group {
  label: Servers and Kubernetes
  direction: down

  Server 1: {
    class: server
    kube1: Kubernetes 1 {class: k8s}
  }
  Server 2: {
    class: server
    kube2: Kubernetes 2 {class: k8s}
  }
  Server 3: {
    class: server
    kube3: Kubernetes 3 {class: k8s}
  }
}

# Storage setup
Server 1 -> storage_network
Server 2 -> storage_network
Server 3 -> storage_network

storage_network: Network {class: network}

storage: {class: storage}
storage_network -> storage
