#  vim:ts=2:sts=2:sw=2:et
name: D2 fmt

on:
  push:
    branches:
      - main
    paths:
      - '*.d2'
      #- Makefile
      - .github/workflows/d2-fmt.yaml  # this workflow

  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  d2_fmt:
    name: D2 fmt
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: ( github.ref_name == 'master' || github.ref_name == 'main' ) && github.event.repository.fork == false

    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Bootstrap
        run: setup/ci_bootstrap.sh

      - name: Install D2 Dependencies
        run: make install-d2

      - name: D2 fmt
        run: make fmt

      - name: Check diff
        run: |
          if ! git diff --quiet; then
            echo "There are formatting changes:"
            echo
            git diff
            exit 1
          fi
