
#
#  https://github.com/austinsonger/generate-diagrams
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/austinsonger
#

# ============================================================================ #
#                                    K i c s
# ============================================================================ #

---
name: Kics

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  kics:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'austinsonger'
    name: Kics
    uses: austinsonger/GitHubActions/.github/workflows/kics.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
