
#  https://github.com/austinsonger/generate-diagrams
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/austinsonger
#

# ============================================================================ #
#                 S e m g r e p   G i t H u b   W o r k f l o w
# ============================================================================ #

# Generates code scanning alerts in GitHub's Security tab -> Code scanning alerts

# https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#github-actions

---
name: Semgrep

on:
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semgrep:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'austinsonger'
    name: Semgrep GitHub Security Tab
    uses: austinsonger/GitHubActions/.github/workflows/semgrep.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
