
#
#  https://github.com/austinsonger/generate-diagrams
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/austinsonger
#

# ============================================================================ #
#                              S o n a r C l o u d
# ============================================================================ #

---
name: SonarCloud

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  SonarCloud:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'austinsonger'
    name: SonarCloud
    uses: austinsonger/GitHubActions/.github/workflows/sonarcloud.yaml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
