
#  https://github.com/austinsonger/generate-diagrams
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/austinsonger
#

# ============================================================================ #
#                              V a l i d a t i o n
# ============================================================================ #

# Run all custom validations against files in the repo

---
name: Validation

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  #schedule:
  #  - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'austinsonger'
    name: Validate
    uses: austinsonger/GitHubActions/.github/workflows/validate.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
